### ISSUE TITLE
'import shell' refactor

### ISSUE THREAD

**Issue by raboof** [badgeteam/ESP32-platform-firmware#111]
Codacy warns when you `import shell`, because it sees that as an unused import, even though in our case we actually execute code on 'import shell'

Perhaps we should introduce a more idiomatic way to trigger dropping to the shell, something like `badge.drop_to_shell()`?

**Comment by renzenicolai** [comment]
We have system.shell() already. For legacy reasons, and also because it is quick to enter on the repl the "import shell" method of invoking a clean shell will stay available.

**Comment by raboof** [comment]
okay
