### ISSUE TITLE
Link to driver documentation in README.md is broken

### ISSUE THREAD

**Issue by qguv** [badgeteam/ESP32-platform-firmware#165]
The link to https://github.com/badgeteam/ESP32-platform-firmware/blob/master/DRIVERS.md is dead.

**Comment by tjclement** [comment]
Thanks for reporting! This was fixed in https://github.com/badgeteam/ESP32-platform-firmware/commit/2cb8d4200c85b5eb1f45b7abaa5e8d3fda2a7e80 just now.
