### ISSUE TITLE
OTA app not fitting Disobey2020 screen

### ISSUE THREAD

**Issue by Zokol** [badgeteam/ESP32-platform-firmware#170]
OTA-update application hides the firmware versions, as the lines are too wide.
This prevents verifying that it has found a new version, as the application tells that "An update is available" even if it is the same version as already installed.

**Comment by renzenicolai** [comment]
I've changed the update check app to print messages better suited for the small screen of the Disobey 2020 badge. Please test current master on your alpha release channel to make sure everything works as intended.
