### ISSUE TITLE
Campzone: rgb.pixel only adds

### ISSUE THREAD

**Issue by sebastius** [badgeteam/ESP32-platform-firmware#52]
rgb.pixel(255,255,255,0,0) works
rgb.pixel(0,0,0,0,0) after that doesnt and requires a clearing of the display

**Comment by Duality4Y** [comment]
So what would be the correct behavior?

When i look at the code i see that indeed the colors are added together.
But are the colors supposed to be set to 0 when you call say rgb.pixel((0, 0, 0), (0, 0))?

What i see is that the rgb code uses the compositor and that the compositor layers all this pixel data together by adding them together like so:
https://github.com/badgeteam/ESP32-platform-firmware/blob/19960d2dada37f766002c9322ca45464e2b30f57/firmware/components/driver_display_hub75/compositor.c#L182-L188
so rgb.pixel((0, 0, 0), (0, 0)) effectively adds nothing that is why it doesn't clear/turn off.

Something i noticed i could do is something like this:

``` python
rgb.pixel((0xff, 0xff, 0xff), (0, 0)) # turns on pixel at 0, 0
rgb.pixel((-0xff, -0xff, -0xff), (0, 0)) # turns off pixel at 0, 0
```
looking at the documentation:
https://wiki.badge.team/CZ19#Display

it says that the pixel is set to the color given as argument.
but that is clearly wrong as per the code.

**Comment by renzenicolai** [comment]
The RGB API will be replaced by the generic display api soon.

In fact: try this on a campzone badge:

rgb.disablecomp()
display.drawLine(0,0,10,10,0xFF0000)
display.flush()

:-)
