### ISSUE TITLE
Callbacks from C to MicroPython cause crashes in some situations

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/ESP32-platform-firmware#69]
When using callbacks to functions in classes the function might move in memory, causing the badge to crash when jumping to the now nonexistent function pointer.

Might also happen with globally defined functions in some situations.

 - Check if a function pointer is valid before scheduling it
 - If possible find a way to get this to work properly

**Comment by Duality4Y** [comment]
Any Way to reproduce?

**Comment by renzenicolai** [comment]
Workaround: only use globally defined functions and add wrappers for use by the app developers.
