### ISSUE TITLE
badge.leds_send_data missing

### ISSUE THREAD

**Issue by raboof** [badgeteam/ESP32-platform-firmware#81]
The original firmware used to have a `badge.leds_send_data` (https://github.com/SHA2017-badge/micropython-esp32/blob/master/esp32/modbadge.c#L732)

Do we already provide an API to drive LED's? If so, we should probably document how to migrate from leds_send_data to the new API.

**Comment by renzenicolai** [comment]
https://github.com/badgeteam/ESP32-platform-firmware/pull/89

**Comment by renzenicolai** [comment]
Solved.
