### ISSUE TITLE
up/down touch buttons in installer do not update display

### ISSUE THREAD

**Issue by raboof** [badgeteam/ESP32-platform-firmware#94]
They actually do work, the eink is just not updated

(on version 742966aa9d967cfbb8e65af777ba64d4ee7c0919)

**Comment by renzenicolai** [comment]
I know, fixed already :-)
Will push soon!

**Comment by raboof** [comment]
Confirmed fixed on master now :+1:  (though it's kinda confusing to close the issue before merging the fix :D )
