### ISSUE TITLE
Add an option reset the badge back to factory defaults via UI

### ISSUE THREAD

**Issue by jhaand** [badgeteam/ESP32-platform-firmware#97]
Add an option to reset the badge back to factory settings from the UI. 

At our hackerspace we use HackerHotel badge for instruction. People learn to hack their way through firmware. like setting up the wifi, install apps and such. It would be nice to reset the badge back to basics after the people are done with them. 

info: https://tdvenlo.nl/wiki/doku.php?id=hh19_badge

**Comment by raboof** [comment]
> At our hackerspace we use HackerHotel badge for instruction. People learn to hack their way through firmware. like setting up the wifi, install apps and such

Cool!

> It would be nice to reset the badge back to basics after the people are done with them.

Would `./erase.sh` do the trick?

**Comment by renzenicolai** [comment]
./erase.sh
./flash.sh
would indeed do the trick, but I prefer having a proper reset function in the firmware. Added to the to-do list ;-)

**Comment by renzenicolai** [comment]
Covered by #104
